### ISSUE TITLE
[Invasion] Task {task-id} for Invasion v2.2.3 generated an exception java.lang.IllegalArgumentException: Entry cannot be longer than 40 characters!

### ISSUE THREAD

**Issue by rodel77** [rodel77/Invasion#1]
`[21:33:06] [Server thread/WARN]: [Invasion] Task #7800 for Invasion v2.2.3 generated an exception
java.lang.IllegalArgumentException: Entry cannot be longer than 40 characters!
at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftObjective.getScore(CraftObjective.java:96) ~[spigotmc-1.10.2-R0.1.jar:git-Spigot-34287db-43ab266]
at mx.com.rodel.invasion.InvasionHandler.run(InvasionHandler.java:124) ~[?:?]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigotmc-1.10.2-R0.1.jar:git-Spigot-34287db-43ab266]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigotmc-1.10.2-R0.1.jar:git-Spigot-34287db-43ab266]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigotmc-1.10.2-R0.1.jar:git-Spigot-34287db-43ab266]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigotmc-1.10.2-R0.1.jar:git-Spigot-34287db-43ab266]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigotmc-1.10.2-R0.1.jar:git-Spigot-34287db-43ab266]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigotmc-1.10.2-R0.1.jar:git-Spigot-34287db-43ab266]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]`

Original report: https://www.spigotmc.org/threads/invasion-2-2-3-metrics-source-code-update.104627/page-3#post-1876864

**Comment by rodel77** [comment]
Fixed in 2.2.4 
**47e60e1a131c5d467fcb64145159de85fb09be41**
