### ISSUE TITLE
Command errors

### ISSUE THREAD

**Issue by rodel77** [rodel77/Invasion#2]
Official report: https://www.spigotmc.org/threads/invasion-2-2-3-metrics-source-code-update.104627/page-3#post-1877636

`Code (Text):
[05:52:37] [Server thread/INFO]: NoChanceSD issued server command: /invasion start
[05:52:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'invasion' in plugin Invasion v2.2.3
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.10.2.jar:git-Paper-847]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.10.2.jar:git-Paper-847]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:672) ~[patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1194) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-847]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-847]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
    at mx.com.rodel.invasion.InvasionManager.startInvasion(InvasionManager.java:51) ~[?:?]
    at mx.com.rodel.commands.InvasionCommand.onCommand(InvasionCommand.java:88) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.10.2.jar:git-Paper-847]
    ... 15 more
Code (Text):
[05:50:58] [Server thread/WARN]: Argument could not be passed.
java.lang.NumberFormatException: For input string: "R"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_91]
    at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_91]
    at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_91]
    at mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:647) ~[Invasion%202.2.3.jar:?]
    at mkremins.fanciful.FancyMessage.send(FancyMessage.java:620) [Invasion%202.2.3.jar:?]
    at mkremins.fanciful.FancyMessage.send(FancyMessage.java:685) [Invasion%202.2.3.jar:?]
    at mx.com.rodel.commands.InvasionCommand.sendCommand(InvasionCommand.java:377) [Invasion%202.2.3.jar:?]
    at mx.com.rodel.commands.InvasionCommand.help(InvasionCommand.java:370) [Invasion%202.2.3.jar:?]
    at mx.com.rodel.commands.InvasionCommand.onCommand(InvasionCommand.java:73) [Invasion%202.2.3.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [patched_1.10.2.jar:git-Paper-847]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.10.2.jar:git-Paper-847]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:672) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1194) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-847]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-847]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Code (Text):
[05:55:28] [Server thread/WARN]: [Invasion] Task #142821 for Invasion v2.2.3 generated an exception
java.lang.NullPointerException
    at mx.com.rodel.invasion.InvasionManager.startInvasion(InvasionManager.java:51) ~[?:?]
    at mx.com.rodel.handlers.TickHandler$1.run(TickHandler.java:57) ~[?:?]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-847]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:781) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-847]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-847]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

**Comment by rodel77** [comment]
Fixed in 2.2.4
